# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - waist
    - shoulder
    - elbow
    - wrist
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  excavator_controller:
    type: effort_controllers/JointPositionController
    joints:
      - waist
      - shoulder
      - elbow
      - wrist
    gains:
      waist:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      shoulder:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      elbow:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wrist:
        p: 100
        d: 1
        i: 1
        i_clamp: 1